---
driver:
  name: pulumi

provisioner:
  name: pulumi

suites:
  - name: test-project-dev-west
    driver:
      stack: dev-west
      config:
        test-project:
          bucket_name: kitchen-pulumi-8009408424
        aws:
          region: us-west-2

  - name: test-project-dev-east
    driver:
      stack: dev-east
      config:
        test-project:
          bucket_name: kitchen-pulumi-9089332077
        aws:
          region: us-east-1
      secrets:
        test-project:
          ssh_key: foo

platforms:
  - name: default
