---
driver:
  name: pulumi

provisioner:
  name: pulumi

suites:
  - name: test-project-dev-west
    driver:
      backend: local
      stack: <%= "dev-west-#{rand(10**10)}" %>
      config_file: custom-stack-config-file.yaml
      refresh_config: true
      config:
        test-project:
          foo: bar
      stack_evolution:
        - config:
            test-project:
              foo: new-value
        - config_file: custom-stack-config-file.yaml


  - name: test-project-dev-east
    driver:
      stack: <%= "dev-west-#{rand(10**10)}" %>
      config:
        test-project:
          bucket_name: kitchen-pulumi-9089332077
        aws:
          region: us-east-1
      secrets:
        test-project:
          ssh_key: foo
      stack_evolution:
        - config_file: custom-stack-config-file.yaml
        - config:
            test-project:
              foo: takes-precedence-over-config-file
          secrets:
            test-project:
              access_key: access.pem

platforms:
  - name: default
