---
driver:
  name: pulumi

provisioner:
  name: pulumi

verifier:
  name: pulumi
  systems:
    - name: test system
      backend: local

platforms:
  - name: test-project-dev-west
    driver:
      backend: local
      test_stack_name: <%= "dev-west-#{rand(10**10)}" %>
      config_file: custom-stack-config-file.yaml
      refresh_config: true
      preserve_config: true
      config:
        test-project:
          foo: bar
      stack_evolution:
        - config:
            test-project:
              foo: new-value
        - config_file: custom-stack-config-file.yaml


  - name: test-project-dev-east
    driver:
      test_stack_name: <%= "dev-east-#{rand(10**10)}" %>
      config_file: dev-east.yaml
      preserve_config: true
      config:
        test-project:
          bucket_name: kitchen-pulumi-9089332077
      secrets:
        test-project:
          ssh_key: foo
      stack_evolution:
        - config_file: custom-stack-config-file.yaml
        - config:
            test-project:
              foo: takes-precedence-over-config-file
          secrets:
            test-project:
              access_key: access.pem

suites:
  - name: default
