---
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'lib/kitchen/pulumi/deep_merge.rb'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Max: 90
Metrics/ClassLength:
  Max: 175
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 21
