---
AllCops:
  TargetRubyVersion: 2.6
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Max: 90
Metrics/ClassLength:
  Max: 125
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
