---

driver:
  name: pulumi

provisioner:
  name: pulumi

suites:
  - name: dev-stack
    driver:
      test_stack_name: dev-stack
      config_file: Pulumi.dev.yaml


platforms:
  - name: serverless-rest-api
