---

driver:
  name: pulumi

provisioner:
  name: pulumi

suites:
  - name: dev-stack
    driver:
      stack: dev
      stack_evolution:
        # This stack evolution will update the stack after its initial
        # update and change the API response text to 'hello, kitchen pulumi'
        - config_file: new_response_config.yaml


platforms:
  - name: serverless-rest-api
