---

driver:
  name: pulumi

provisioner:
  name: pulumi

verifier:
  name: pulumi
  systems:
    - name: default
      backend: local

suites:
  - name: dev-stack
    driver:
      test_stack_name: dev-stack
      config_file: Pulumi.dev.yaml
      stack_evolution:
        - config:
            kitchen-pulumi-azure-functions:
              api_response: hello
        - config:
            kitchen-pulumi-azure-functions:
              api_response: world

platforms:
  - name: azure-functions-test
