version: 2.1

orbs:
  pulumi: pulumi/pulumi@1.0.0

jobs:
  build_24: &build
    docker:
      - image: circleci/ruby:2.4.6-node
    steps:
      - checkout

      # Ensure Pulumi CLI is available for use
      - pulumi/login

      # Install dependencies
      - restore_cache:
          keys:
            - kitchen-pulumi-dependencies-{{ checksum "Gemfile.lock" }}
            - kitchen-pulumi-dependencies
      - run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: kitchen-pulumi-dependencies-{{ checksum "Gemfile.lock" }}

      # Lint
      - run: bundle exec rake lint

      # Run unit tests
      - run: mkdir /tmp/test-results && bundle exec rake npm_install && bundle exec rake spec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  build_25:
    <<: *build
    docker:
      - image: circleci/ruby:2.5.5-node

  build_26:
    <<: *build
    docker:
      - image: circleci/ruby:2.6.2-node


workflows:
  build:
    jobs:
      - build_24
      - build_25
      - build_26
