version: 2
jobs:
  setup:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies
      - run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  lint:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: vendor/bundle
      - run: bundle exec rake lint

  test:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: vendor/bundle
      - run: mkdir /tmp/test-results && bundle exec rake spec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
